config/routes.rb
Rails.application.routes.draw do
  get 'movie/index'
  get 'importer', to: 'importer#import_file'
  post 'importer', to: 'importer#parse_csv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews
    scope :actor_search, -> (actor) {where("lower(actor) LIKE ?", "%#{actor.try(:downcase)}%")}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/importer_controller.rb
class ImporterController < ApplicationController
  def import_file
  end

  def parse_csv
    @result = CsvDb.convert_save(params[:dump][:model_name],params[:dump][:file])
    
    if @result[:success]
      flash[:notice] = @result[:message]
      redirect_to action: :import_file, notice: "CSV imported successfully!"
     else
      flash[:error] = @result[:message]
      redirect_to action: 'import_file'
     end
     
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  def index
    @movies = Movie.includes(:reviews).actor_search(params[:actor])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/importer/import_file.html.erb
<% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>
  
<%= form_for :dump, :url => {:action => "parse_csv"}, :html => {:multipart => true} do |f| %>
	<fieldset class="inputs">
		<legend><span>Select a CSV File</span></legend>
        <ol>
        <li class="datepicker input required stringish" >
        <%= f.select :model_name, options_for_select([["Select One", ""], "Movie","Review"]), :class => 'genForm_dropBox' %>
        </li>
			<li class="datepicker input required stringish" >
				<%= f.file_field :file %>
			</li>
		</ol>
	</fieldset>
	<fieldset class="actions">
		<li class="action input_action " id="daily_report_submit_action">
			<%= submit_tag 'Submit' %>
		</li>
	</fieldset>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qidz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movie/index.html.erb
<%= form_tag(movie_index_path, :method => 'get') do %>

    <div class="field">
      <%= label_tag :actor, "Actor Search"%>
      <%= text_field_tag :actor%>
    </div>
    <div class="actions"><%= submit_tag "Search" %></div>
  <% end %>

  <table id="Movies">
    <tr>
      <th><%= "Movie Name" %></th>
      <th><%= "Description" %></th>
      <th><%= "Year" %></th>
      <th><%= "Director" %></th>
      <th><%= "Actor" %></th>
      <th><%= "Filming location" %></th>
      <th><%= "Country" %></th>

    </tr>
    <% @movies.each do |movie| %>
    <tr>
    <td><%= movie.movie %></td>
    <td><%= movie.description %></td>
    <td><%= movie.year %></td>
    <td><%= movie.director %></td>
    <td><%= movie.actor %></td>
    <td><%= movie.filming_location %></td>
    <td><%= movie.country %></td>

    </tr>  
     <% end %>


  </table>